travis:
  secure:
    BINSTAR_TOKEN: HTsDTpgPZNZy7TkrMjMkcgGX/y8Bq/J4KhDkmbuy5ixegY2G4ovoy8HLS1+g75lCu7/wCHhYx2T9z+SJmy1b9qlMlDn9iXCQL8NFSs+IVQQRG2SMmtC8hnxJqAKOZoZi0T3Dsp5lp3C3GCKw0LZTRQc73jgWyhCtlKsUDB2tUlGRCeY2yBXXw+eEcwzJIRTw5JMqkrtkg9azw+dFJAT9Gw7lw7rT4c1Zm5xFunBDcF5Mrj2PBMarzeGhvGGDkdifxSkzOlT8LyrOCFMsyOkzWgHklmJT36qH3xALORAZU1uq8o4yjyYGQqIcZsollFl2cneGa0RniotvljbJCtph01qWc2uf5DmJHv1VHA43sRGkce8iulzacoAuXJKx8gM2h/CklnoQcw44Zb0TAG/Eh2pe8l0wOGHjGhYVvu5D2+8m5pYE74s18i9t2j0wOfLNjFkuSGuDn+eLGbsf3QCrBdrsPYZs4m19Mnn+oABKW/dkL8ilIbr2blsUcVx08XJsFrUBxSZL47ThJlODeGZR9F3gzuyxHDK6QuU8JD26lsLIuxb+o0jFiNykHPb035osBgkziq+KFYNK9Mh6AxJUgiFIQDl+1TUpJMgPmaoK7jGU2H1ysJS7BwOBLf6ccDmx+tR5umR19diTVn9iKW4ht5rBjleEn2JT7sszoyOkHRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
